class CreateAnAccountPage:
    MR_RADIO_BUTTON = "input[name='id_gender']"
    FIRST_NAME_INPUT = "input[name='customer_firstname']"
    LAST_NAME_INPUT = "input[name='customer_lastname']"
    EMAIL_INPUT = "input[name='email']"
    PASSWORD_INPUT = "input[name='passwd']"
    DAYS_SELECT = "select[name='days']"
    MONTHS_SELECT = "select[name='months']"
    YEARS_SELECT = "select[name='years']"
    REGISTER_BUTTON = "button:has-text('Register')"
